package server

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"
)

// a transcript's first lines the way the CLI writes them: the mode
// stamps, a meta caveat, a slash command and its output, then the prompt
func writeClaudeTranscript(t *testing.T, home, folder, id, entrypoint, cwd, prompt string, mtime time.Time) string {
	t.Helper()
	dir := filepath.Join(home, "projects", folder)
	os.MkdirAll(dir, 0o755)
	path := filepath.Join(dir, id+".jsonl")
	user := func(content, extra string) string {
		return `{"parentUuid":null,"isSidechain":false,"type":"user","message":{"role":"user","content":` + content + `}` + extra +
			`,"uuid":"u1","timestamp":"2026-09-23T06:53:13.158Z","userType":"external","entrypoint":"` + entrypoint + `","cwd":"` + cwd + `","sessionId":"` + id + `","version":"2.1.263"}` + "\n"
	}
	body := `{"type":"mode","mode":"normal","sessionId":"` + id + `"}` + "\n" +
		`{"type":"permission-mode","permissionMode":"auto","sessionId":"` + id + `"}` + "\n" +
		user(`"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"`, `,"isMeta":true`) +
		user(`"<command-name>/model</command-name>\n<command-message>model</command-message>"`, "") +
		user(`"<local-command-stdout>Set model to Fable 5.1</local-command-stdout>"`, "") +
		user(`[{"type":"text","text":"<system-reminder>\nAs you answer, use this context\n</system-reminder>"},{"type":"text","text":"`+prompt+`"}]`, "") +
		`{"parentUuid":"u1","type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"Sure."}]},"uuid":"a1","timestamp":"2026-09-23T06:53:20.000Z"}` + "\n" +
		user(`[{"type":"tool_result","tool_use_id":"t1","content":"ok"}]`, "")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	os.Chtimes(path, mtime, mtime)
	return path
}

func appendLine(t *testing.T, path, line string, mtime time.Time) {
	t.Helper()
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	f.WriteString(line + "\n")
	f.Close()
	os.Chtimes(path, mtime, mtime)
}

func TestClaudeSessions(t *testing.T) {
	home := t.TempDir()
	now := time.Date(2026, 9, 23, 7, 0, 0, 0, time.UTC)
	mine := "81afe071-7e89-4ee7-9522-b7e0ca11f6b6"
	minePath := writeClaudeTranscript(t, home, "-www-exe", mine, "cli", "/www/exe",
		"exe webui: right click on desktop can open a customizable menu, and right now one of the options is btop", now.Add(-3*time.Second))
	// a headless run (the hub watcher's turn): not listed
	writeClaudeTranscript(t, home, "-www-exe", "c8570b33-0815-5847-9e9b-97c75876f60f", "sdk-cli", "/www/exe", "You are Claude, running the nightly idea routine", now)
	// an older session in another folder, titled by the CLI
	old := "1ed4e4cb-3cb0-485c-a683-867f1bf90458"
	oldPath := writeClaudeTranscript(t, home, "-www-exe-city", old, "cli", "/www/exe-city", "add a tornado to the city", now.Add(-4*24*time.Hour))
	appendLine(t, oldPath, `{"type":"ai-title","aiTitle":"City tornado disaster","sessionId":"`+old+`"}`, now.Add(-4*24*time.Hour))
	// a session with no prompt yet (the CLI just opened): not listed
	fresh := filepath.Join(home, "projects", "-www-exe", "0d359ee3-d1e6-4373-a7d3-c74eb871a203.jsonl")
	os.WriteFile(fresh, []byte(`{"type":"mode","mode":"normal","sessionId":"0d359ee3-d1e6-4373-a7d3-c74eb871a203"}`+"\n"), 0o644)
	// a sub-agent's transcript, a folder down: not a session
	sub := filepath.Join(home, "projects", "-www-exe", mine, "subagents")
	os.MkdirAll(sub, 0o755)
	os.WriteFile(filepath.Join(sub, "agent-abc.jsonl"), []byte(`{"type":"user","message":{"role":"user","content":"sub"},"entrypoint":"cli","cwd":"/www/exe","timestamp":"2026-09-23T06:53:13.158Z"}`+"\n"), 0o644)
	// memory notes and the like beside the transcripts: not sessions
	os.WriteFile(filepath.Join(home, "projects", "-www-exe", "notes.jsonl"), []byte("{}\n"), 0o644)

	list := claudeSessions(home, nil, nil, now, claudeSessionsShown)
	if len(list) != 2 {
		t.Fatalf("sessions: %+v", list)
	}
	if l := list[0]; l.ID != mine || l.Title != "exe webui: right click on desktop can open a customizable me…" || l.Origin != "a terminal" ||
		l.Cwd != "/www/exe" || !l.Working || l.Open || l.Activity != now.Add(-3*time.Second).Unix() ||
		l.Created != time.Date(2026, 9, 23, 6, 53, 13, 0, time.UTC).Unix() {
		t.Fatalf("my session: %+v", l)
	}
	if l := list[1]; l.ID != old || l.Title != "City tornado disaster" || l.Cwd != "/www/exe-city" || l.Working {
		t.Fatalf("older session: %+v", l)
	}
	// a session of the column's carries mine: left out, and its file is never read
	claudeMetaCache.Delete(minePath)
	if list = claudeSessions(home, map[string]bool{mine: true}, nil, now, claudeSessionsShown); len(list) != 1 || list[0].ID != old {
		t.Fatalf("with mine live: %+v", list)
	}
	if _, ok := claudeMetaCache.Load(minePath); ok {
		t.Fatal("a live session's transcript was read")
	}
	// open elsewhere: marked
	if list = claudeSessions(home, nil, map[string]bool{mine: true}, now, claudeSessionsShown); !list[0].Open {
		t.Fatalf("open: %+v", list)
	}
	// the cap
	if list = claudeSessions(home, nil, nil, now, 1); len(list) != 1 || list[0].ID != mine {
		t.Fatalf("capped: %+v", list)
	}
	// a title that arrives later is picked up: the file grew, so it is read again;
	// the person's own name outranks the CLI's
	appendLine(t, oldPath, `{"type":"ai-title","aiTitle":"Tornado, take two","sessionId":"`+old+`"}`, now.Add(-time.Hour))
	appendLine(t, oldPath, `{"type":"custom-title","customTitle":"city-tornado","sessionId":"`+old+`"}`, now.Add(-time.Hour))
	if list = claudeSessions(home, nil, nil, now, 0); len(list) != 2 || list[1].Title != "city-tornado" {
		t.Fatalf("renamed: %+v", list)
	}
	// by id, for a resume
	if s := claudeSessionByID(home, old); s == nil || s.cwd != "/www/exe-city" || s.path != oldPath {
		t.Fatalf("by id: %+v", s)
	}
	if s := claudeSessionByID(home, "ffffffff-0000-4000-8000-000000000000"); s != nil {
		t.Fatalf("unknown id: %+v", s)
	}
	if s := claudeSessionByID(home, "../x"); s != nil {
		t.Fatalf("bad id: %+v", s)
	}
	// no home, an empty home: nothing, quietly
	if list = claudeSessions("", nil, nil, now, 5); len(list) != 0 {
		t.Fatalf("no home: %+v", list)
	}
	if list = claudeSessions(t.TempDir(), nil, nil, now, 5); len(list) != 0 {
		t.Fatalf("empty home: %+v", list)
	}
}

func TestClaudeOpenSessions(t *testing.T) {
	home := t.TempDir()
	dir := filepath.Join(home, "sessions")
	os.MkdirAll(dir, 0o755)
	me := os.Getpid()
	// this process's own start, the way the CLI records its own
	start := ""
	if b, err := os.ReadFile("/proc/self/stat"); err == nil {
		s := string(b)
		start = strings.Fields(s[strings.LastIndexByte(s, ')')+1:])[19]
	}
	rec := func(name string, pid int, id, procStart string) {
		os.WriteFile(filepath.Join(dir, name), []byte(`{"pid":`+strconv.Itoa(pid)+`,"sessionId":"`+id+`","cwd":"/www/exe","startedAt":1790057102988,"procStart":"`+procStart+`","kind":"interactive","entrypoint":"cli"}`), 0o644)
		os.WriteFile(filepath.Join(dir, name+".key"), []byte("k"), 0o644)
	}
	rec(strconv.Itoa(me)+".json", me, "aaaaaaaa-0000-4000-8000-000000000001", start)
	rec("999999999.json", 999999999, "aaaaaaaa-0000-4000-8000-000000000002", "1") // no such process
	if start != "" {
		rec("2.json", me, "aaaaaaaa-0000-4000-8000-000000000003", "1") // the pid, reused: another start
	}
	os.WriteFile(filepath.Join(dir, "bad.json"), []byte("not json"), 0o644)
	open := claudeOpenSessions(home)
	if !open["aaaaaaaa-0000-4000-8000-000000000001"] || open["aaaaaaaa-0000-4000-8000-000000000002"] || open["aaaaaaaa-0000-4000-8000-000000000003"] || len(open) != 1 {
		t.Fatalf("open: %v", open)
	}
	if len(claudeOpenSessions(t.TempDir())) != 0 || len(claudeOpenSessions("")) != 0 {
		t.Fatal("no records: nothing")
	}
}

func TestNoteClaudeSession(t *testing.T) {
	s := &Server{StateDir: t.TempDir()}
	a := hostAgents["claude"]
	transcript := filepath.Join(t.TempDir(), "81afe071-7e89-4ee7-9522-b7e0ca11f6b6.jsonl")
	os.WriteFile(transcript, []byte("{}\n"), 0o644)
	s.noteClaudeSession(a, "exe-claude-3", "81afe071-7e89-4ee7-9522-b7e0ca11f6b6", transcript)
	file := s.agentStatusFile(a, "exe-claude-3")
	if got := readAgentThreadID(file); got != "81afe071-7e89-4ee7-9522-b7e0ca11f6b6" {
		t.Fatalf("stub: %q", got)
	}
	if !readAgentResumable(file) {
		t.Fatal("a resumed session is resumable from the start")
	}
	// the hook's own JSON reads the same way
	os.WriteFile(file, []byte(`{"session_id":"deadbeef-0000-4000-8000-000000000000","transcript_path":"`+transcript+`","context_window":{"total_input_tokens":12}}`), 0o644)
	if got := readAgentThreadID(file); got != "deadbeef-0000-4000-8000-000000000000" {
		t.Fatalf("hook JSON: %q", got)
	}
}
